### PR TITLE
Update to Foundry 11.309

### PR DESCRIPTION
**Pull request by MatteoJoliveau**
As title says. Tested on my private instance, works like a charm.

### CODE REVIEW

**Comment by reckenrode** [comment]
I’d like to move forward with #15. Are you able to test that branch? I’ve added 11.309 to the PR.

**Comment by reckenrode** [comment]
Why is pixi.js pinned? Are minor updates not compatible?

If not, I’ll need to modify the update script in #15 to rewrite the version bound to limit versions to patch updates.

**Comment by MatteoJoliveau** [comment]
Oops sorry for the very late reply, I missed the GH notifications.

Pixi is pinned because the kind folks at Foundry have included this bit of code in `foundry.js` which makes it throw a rather unhelpful error if Pixi is ever newer than 7.3.0, but kept the `^7.2.4` version bound in `package.json`.

image


I guess none of the "regular" users experienced this problem because the Zip file vendors the entire node_modules directory, but we found out because we built our own via node2nix.

Re: #15 , I will review it as soon as possible but I probably won't be able to test the branch before next Wednesday because I have a game on Tuesday night I don't want to jeopardise (the Pixi issue was already too close to the session for my tastes :D, but I needed to update for compatibility with some modules).

**Comment by MatteoJoliveau** [comment]
I plan on opening an issue on foundry itself as soon as I have the time to collect more context

**Comment by reckenrode** [comment]
Thanks for the explanation. I can put in a workaround to limit pixi.js to patch upgrades regardless of the bounds specified in the dependencies. I assume Foundry has gotten bit by upgrades in the past and put the code in place as a defensive measure (or to discourage users from messing with dependencies and asking for support).

Regarding #15, if you need extra time to test, I can wait to merge. I just don’t want to keep it open indefinitely without any user testing or feedback.

**Comment by MatteoJoliveau** [comment]
I can try it on Wednesday evening (CEST). I don't see anything wrong with the changes at first glance, so I wouldn't expect major issues at runtime. The Pixi version is the only disruptive problem I've seen so far, so provided that gets fixed I'm ok with closing this PR and folding back to #15

I'll comment there after I've updated my instance and confirmed everything's fine 👍🏻

**Comment by reckenrode** [comment]
Closing since this was implemented in #15.

**Pull request closed without merging**
