### PR TITLE
Update Foundry and NixOS versions + some small QoL changes

### PR DESCRIPTION
**Pull request by MatteoJoliveau**
Hi! Thank you so much for this module, I just used it to set up my own server and it's working great!

I had to make a few changes in order to update both NixOS (to 22.11) and Foundry (to build 291), and I took the opportunity to improve some parts for a better experience.

- Added a default package reference since it's the only one exported by the flake
- Added an unfree exclusion for `pngout` to avoid having to pass environment variables like `NIXPKGS_ALLOW_UNFREE`
- Added a `dataDir` option to the nixos module so that it can be referenced elsewhere (I use it to automatically configure the backup job)
- Change the restart policy to `always` so that systemd restarts the server correctly when it exits cleanly, for example when the server stops after installing some modules and requires a restart. The server can still be stopped manually via `systemctl stop foundryvtt`

### CODE REVIEW

**Comment by reckenrode** [comment]
These changes look pretty reasonable. Can you also bump the Foundry dependencies? It also usually includes updates to those with a new release.

**Comment by MatteoJoliveau** [comment]
Yeah sure! Do you have any recommendation about running `node2nix`? I tried running it against the `package.json` from Foundry 291 but got this error

```
$ node2nix

fetching local directory: ./. from .
info attempt registry request try #1 at 10:22:31 PM
http request GET https://registry.npmjs.org/@foundryvtt%2Fpdfjs
http 404 https://registry.npmjs.org/@foundryvtt%2Fpdfjs
Error: Not found : @foundryvtt/pdfjs
```

**Comment by reckenrode** [comment]
> Yeah sure! Do you have any recommendation about running `node2nix`? I tried running it against the `package.json` from Foundry 291 but got this error

Foundry is using a fork of pdfjs, which is available at https://github.com/foundryvtt/pdfjs. I believe it’s also available via the GitHub package registry, but that requires additional configuration and a GitHub token.

What I’ve done in the past is replaced the dependency on the GitHub repo. [This][1] commit corresponds to the version in `packages.json`. After I run `node2nix`, I fix up the references manually to work with the unmodified `packages.js`.

It’s not ideal. One of the things I want to fix in issue #6 is automating dependency bumps. That it’s an annoyingly manual process is why this repo has been slow to update at times.

[1]: https://github.com/foundryvtt/pdfjs/commit/2196ae9bcbd8d6a9b0b9c493d0e9f3aca13f2fd9

**Comment by reckenrode** [comment]
Thanks for the quick update to the PR! I did a local build, and it looks good.

Before merging, can you fixup [91623f6](https://github.com/reckenrode/nix-foundryvtt/pull/5/commits/91623f6a620af4fe59d8d230858bb15fe58061c5) with [f6de44e](https://github.com/reckenrode/nix-foundryvtt/pull/5/commits/f6de44e62102b98519c9c75df62978e2fcba215b) and fixup [f1b1d1a](https://github.com/reckenrode/nix-foundryvtt/pull/5/commits/f1b1d1a42025e4041fe5656b5ba0ece6bcfe3b4c) with [d723faa](https://github.com/reckenrode/nix-foundryvtt/pull/5/commits/d723faa4f0b1c7f899bc068bd86d2cdbd989fe60)?

**Comment by JonBoyleCoding** [comment]
Just to note, for 22.11 the networking.hostname has a different case:

https://search.nixos.org/options?channel=22.11&show=networking.hostName&from=0&size=50&sort=relevance&type=packages&query=networking.hostname

This is referenced in the default configuration.

**Comment by MatteoJoliveau** [comment]
Right, I'm going to fix it right now. Do you want to (breaking) change the `services.foundryvtt.hostname` param as well to align with `networking.hostName` or do you feel it's not worth it?

**Comment by MatteoJoliveau** [comment]
@reckenrode to avoid doing too much git surgery I'm just going to squash all the commits into one if it's ok with you

**Comment by reckenrode** [comment]
If it’s okay, I’d rather merge it as-is than squash.

**Comment by MatteoJoliveau** [comment]
@reckenrode done!

What about the hostname thing? Should I rename the option to `hostName` or not?

**Comment by reckenrode** [comment]
> What about the hostname thing? Should I rename the option to hostName or not?

I agree with the change, but I’d like to do it separately. I can push that change once this PR is merged. I don’t want to break configs, so I’ll include a warning to use the new name and remove the old one coinciding with the 23.11 release of NixOS.

**Comment by reckenrode** [comment]
Thank you for the contribution! It’s been merged.

**Pull request merged**
